version: "3"
services:
    wordpress:
        build: .
        depends_on:
          - db
        ports:
          - "9002:80"
        volumes:
          - ./:/var/www/html
    db:
        image: mariadb:10.5.8
        ports:
          - "4308:3306"
        environment:
            MYSQL_ROOT_HOST: "0.0.0.0"
            # MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        volumes:
          - ./data/mysql:/var/lib/mysql:rw,delegated
        restart: always